---
title: "Disaster Prepositioning Case Study"
author: "Your Name"
repository: https://github.com/yurchisin/case-studies/tree/main/esups/
binder:
  url: "https://mybinder.org"
execute:
  execute_notebooks: "force"
